#!/bin/bash
cd "$(dirname "$0")"
pwd

# https://abhibvp003.medium.com/how-to-install-and-execute-truffle-on-an-ubuntu-16-04-7d0ff6458c9b
# https://cdmana.com/2021/05/20210506173242922f.html
# https://nodejs.org/en/about/releases/


echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log

apt -y install curl git vim build-essential
#apt -y install curl software-properties-common
#apt -y install gcc g++ make

curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
apt -y install nodejs
#apt -y install npm
apt -y autoremove

nodejs -v
npm -v

