#!/bin/bash
pushd "$(dirname "$0")"
pwd

echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log

ufw allow 22
ufw enable 

./010_init_upgrade
./020_init_essentials
./030_init_jupyter
./040_init_vim
./090_init_config

screenfetch
popd
