#!/bin/bash
pushd "$(dirname "$0")"

echo ************************************
echo RUNNING "$0"
echo ************************************
echo "$0" >> ~/install.log

./010_init_upgrade
./020_init_essentials
./030_init_jupyter
./090_init_config

popd
