#!/bin/bash
pushd "$(dirname "$0")"
pwd

echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log


echo 010_init > ~/install.log
apt -y update
apt -y upgrade
apt -y autoremove

popd
