#!/bin/bash
pushd "$(dirname "$0")"
pwd

echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log


apt -y install git
apt -y install supervisor
apt -y install build-essential
apt -y install bc
apt -y install mosh
apt -y install screenfetch
apt -y install tree

# https://www.digitalocean.com/community/tutorials/how-to-install-postgresql-on-ubuntu-20-04-quickstart
apt -y install postgresql postgresql-contrib
# systemctl restart postgresql.service
# systemctl enable postgresql.service
# sudo -i -u postgres
# psql
# ALTER USER postgres WITH PASSWORD 'postgres';
# ALTER USER postgres WITH PASSWORD 'b2742bade1f3a271c55eef069e2f19903aa0740c';
# quit
# exit




popd
