#!/bin/bash
pushd "$(dirname "$0")"
pwd

echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log


#apt -y install git
apt -y install supervisor
apt -y install build-essential
apt -y install bc
apt -y install mosh
apt -y install screenfetch
apt -y install tree


pip3 install pyqrcode

popd
