#!/bin/bash
pushd "$(dirname "$0")"
pwd

echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log

apt -y install python3 python3-pip
apt -y install python-is-python3
apt -y install python3-dev

pip3 install --upgrade pip
pip3 install jupyterlab
pip3 install jupytext

#jupyter notebook --allow-root
#jupyter notebook --port=9999 --allow-root

pip3 install pytest
pip3 install setuptools
pip3 install requests
pip3 install python-dotenv
pip3 install click
#pip3 install dataclass_wizard


pip3 install pandas
pip3 install numpy
pip3 install scipy
pip3 install matplotlib
pip3 install tabulate
pip3 install cvxpy
pip3 install networkx

pip3 install sqlalchemy
pip3 install alchemy-sdk
pip3 install psycopg2-binary
#pip3 install  psycopg2
#pip3 install pyarrow
#pip3 install fastparquet

pip3 install eth-brownie
pip3 install web3
pip3 install hexbytes

pip3 install joblib
pip3 install psutil

#pip3 install pyqrcode

popd
