#!/bin/bash
pushd "$(dirname "$0")"

echo ************************************
echo RUNNING "$0"
echo ************************************
echo "$0" >> ~/install.log

apt -y install python3 python3-pip
pip3 install --upgrade pip
pip3 install jupyter
#jupyter notebook --allow-root

popd
