#!/bin/bash
pushd "$(dirname "$0")"
pwd

echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log

cp ../_etc/home/vimrc ~/.vimrc



mkdir -p ~/.vim/pack/bundle/start

pushd ~/.vim/pack/bundle/start
git clone https://github.com/tomlion/vim-solidity.git
popd

# http://ctrlpvim.github.io/ctrlp.vim/#installation
#

pushd ~/.vim
git clone https://github.com/ctrlpvim/ctrlp.vim.git bundle/ctrlp.vim
popd

echo  RUN :helptags ~/.vim/bundle/ctrlp.vim/doc in vim

popd
