#!/bin/bash
cd "$(dirname "$0")"

echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log


# https://www.digitalocean.com/community/tutorials/how-to-install-ruby-and-set-up-a-local-programming-environment-on-ubuntu-16-04
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://get.rvm.io -o rvm.sh
cat rvm.sh | bash -s stable
rm rvm.sh

#source ~/.rvm/scripts/rvm
source /etc/profile.d/rvm.sh
rvm install ruby --default
