#!/bin/bash
cd "$(dirname "$0")"

echo ************************************
echo RUNNING "$0"
echo ************************************
echo "$0" >> ~/install.log

# https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
source ~/.bashrc

nvm list-remote
nvm install lts/gallium
nvm list
