#!/bin/bash
cd "$(dirname "$0")"

echo ************************************
echo RUNNING "$0"
echo ************************************
echo "$0" >> ~/install.log


curl -sSL https://get.haskellstack.org/ | sh
stack ghci
