#!/bin/bash
cd "$(dirname "$0")"

# https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04
# https://github.com/nodesource/distributions

cd ~
curl -sL https://deb.nodesource.com/setup_9.x -o nodesource_setup.sh
bash nodesource_setup.sh
apt -y install nodejs
#apt -y install build-essential

nodejs -v
npm -v
