#!/bin/bash
cd "$(dirname "$0")"

echo ************************************
echo RUNNING "$0"
echo ************************************
echo "$0" >> ~/install.log


# https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04
# https://github.com/nodesource/distributions
#https://websiteforstudents.com/install-the-latest-node-js-and-nmp-packages-on-ubuntu-16-04-18-04-lts/

cd ~
#curl -sL https://deb.nodesource.com/setup_9.x -o nodesource_setup.sh
#bash nodesource_setup.sh
curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
apt -y install nodejs
#apt -y install build-essential

nodejs -v
npm -v
