#!/bin/bash
cd "$(dirname "$0")"
pwd

echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log


apt -y update
apt -y install python3 python3-pip
apt -y install python3-virtualenv
pip3 install --upgrade pip

python3 --version
pip3 --version
