#!/bin/bash
cd "$(dirname "$0")"

apt -y update
apt -y install python3 python3-pip
apt -y install python3-virtualenv
pip3 install --upgrade pip
pip3 install django

python3 --version
pip3 --version
python3 -m django --version
