#!/bin/bash
cd "$(dirname "$0")"
pwd

echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log


pip3 install jupyter
pip3 install matplotlib
pip3 install pandas
pip3 install pixiedust
pip3 install pixiedust_node
