#!/bin/bash
cd "$(dirname "$0")"

echo ************************************
echo RUNNING "$0"
echo ************************************
echo "$0" >> ~/install.log


# https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-vnc-on-ubuntu-16-04

apt update

apt -y install xfce4 xfce4-goodies
apt -y install tightvncserver

mkdir ~/.vnc
cp ../_etc/vnc_xstartup ~/.vnc/xstartup
chmod +x ~/.vnc/xstartup

echo
echo
echo ==============================================
echo YOU MUST NOW ENTER A PASSWORD
echo ==============================================
echo
vncserver
