#!/bin/bash
cd "$(dirname "$0")"

# https://askubuntu.com/questions/6339/how-do-i-install-the-latest-stable-version-of-firefox
# https://help.ubuntu.com/community/FirefoxNewVersion

apt -y install firefox
