#!/bin/bash
cd "$(dirname "$0")"

echo ************************************
echo RUNNING "$0"
echo ************************************
echo "$0" >> ~/install.log

# https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-apache-on-ubuntu-16-04


apt -y install apache2
apt -y install apache2-utils
apt -y install libapache2-mod-wsgi

#htpasswd -c /etc/apache2/.htpasswd skl
#cat /etc/apache2/.htpasswd

#AuthType Basic
#AuthName "Restricted Content"
#AuthUserFile /etc/apache2/.htpasswd
#Require valid-user

mkdir -p /root/bin

cat << EOF > /root/bin/a2start
systemctl start apache2
EOF

cat << EOF > /root/bin/a2stop
systemctl stop apache2
EOF

cat << EOF > /root/bin/a2reload
systemctl reload apache2
EOF

cat << EOF > nul
<VirtualHost _default_:443>

    DocumentRoot /var/www/htmls
    ErrorLog /var/log/apache2/error_selfsigned.log
    CustomLog /var/log/apache2/access_selfsigned.log combined
    SSLEngine on
    SSLCertificateFile    /etc/apache2/certs/selfsigned.crt
    SSLCertificateKeyFile /etc/apache2/certs/selfsigned.key
    IndexIgnore *
    Options +Indexes +FollowSymLinks

</VirtualHost>

<Directory "/var/www/htmls">

    Options -Indexes -FollowSymLinks

    AuthType Basic
    AuthName "Restricted Content"
    AuthUserFile /etc/apache2/.htpasswd
    Require valid-user

</Directory>
EOF

chmod +x /root/bin/a2*
