#!/bin/bash
cd "$(dirname "$0")"

echo ************************************
echo RUNNING "$0"
echo ************************************
echo "$0" >> ~/install.log


apt -y install certbot
mkdir -p /etc/apache2/certs



openssl dhparam -out /etc/apache2/certs/dhparam.pem 2048

mkdir -p /var/lib/letsencrypt/.well-known
chgrp www-data /var/lib/letsencrypt
chmod g+s /var/lib/letsencrypt

cat << EOF > /etc/apache2/conf-available/letsencrypt.conf

Alias /.well-known/acme-challenge/ "/var/lib/letsencrypt/.well-known/acme-challenge/"
<Directory "/var/lib/letsencrypt/">
    AllowOverride None
    Options MultiViews Indexes SymLinksIfOwnerMatch IncludesNoExec
    Require method GET POST OPTIONS
</Directory>

EOF


cat << EOF > /etc/apache2/conf-available/ssl-params.conf

SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
SSLHonorCipherOrder On
Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
Header always set X-Frame-Options DENY
Header always set X-Content-Type-Options nosniff
# Requires Apache >= 2.4
SSLCompression off
SSLUseStapling on
SSLStaplingCache "shmcb:logs/stapling-cache(150000)"
# Requires Apache >= 2.4.11
SSLSessionTickets Off
SSLOpenSSLConfCmd DHParameters "/etc/apache2/certs/dhparam.pem"

EOF

a2enmod ssl
a2enmod headers

a2enconf letsencrypt
a2enconf ssl-params

a2enmod http2

systemctl reload apache2

# certbot certonly --agree-tos --email admin@example.com --webroot -w /var/lib/letsencrypt/ -d example.com -d www.example.com
#certbot certonly --agree-tos --email noreply@virtcard.co --webroot -w /var/lib/letsencrypt/ -d notes.virtcard.co
