#!/bin/bash
cd "$(dirname "$0")"

echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log




apt -y install git
apt -y install supervisor
apt -y install build-essential
apt -y install bc
apt -y install mosh
apt -y install screenfetch
apt -y install tree
pip3 install pyqrcode

# https://www.digitalocean.com/community/tutorials/how-to-install-postgresql-on-ubuntu-20-04-quickstart
apt -y install postgresql postgresql-contrib
# systemctl start postgresql.service
# sudo -i -u postgres
# psql
# ALTER USER postgres WITH PASSWORD 'postgres';
# ALTER USER postgres WITH PASSWORD 'b2742bade1f3a271c55eef069e2f19903aa0740c';
# quit
# exit

cd ~
mkdir CarbonSimulator
mkdir Arbbot
pushd CarbonSimulator
git init
popd
pushd Arbbot
git init
popd


`
git remote add a3 root@64.226.101.44:/root/CarbonSimulator
git remote add a3 root@64.226.101.44:/root/Arbbot
git remote add a3 root@64.226.101.44:/root/config
git remote remove a3
`

# ;*******************************************************************
# ; carbon_fastlane
# ;*******************************************************************
# [program:carbon_fastlane]
# command=/root/Arbbot/run_supervisor
# autostart=true
# autorestart=true
# startsecs=10
# startretries=3
# killasgroup=true
# stopasgroup=true
# redirect_stderr=false
# stdout_logfile=/var/log/carbon_fastlane_output.log
# stderr_logfile=/var/log/carbon_fastlane_error.log

# pg_hba.conf
# host all all 77.101.165.176/0 trust
# host all all 103.209.254.100/0 trust

# postgresql.conf
# listen_addresses = '*'