#!/bin/bash
pushd "$(dirname "$0")"
pwd

# Target: Ubuntu 20.04 (August 2021)


echo "************************************"
echo RUNNING "$0"
echo "************************************"
echo "$0" >> ~/install.log


# http://www.techtonet.com/how-to-install-and-execute-truffle-on-an-ubuntu-16-04/
# https://abhibvp003.medium.com/how-to-install-and-execute-truffle-on-an-ubuntu-16-04-7d0ff6458c9b
# https://cdmana.com/2021/05/20210506173242922f.html
# https://nodejs.org/en/about/releases/


echo ====================================================
echo INSTALLING BASICS
echo ====================================================

../components/000_init
apt -y install curl vim build-essential


echo ====================================================
echo INSTALLING NODE
echo ====================================================

#source ../components/100_node_ppa
source ../components/100_node_apt

echo ====================================================
echo INSTALLING ETHEREUM DEV
echo ====================================================

# ethereumjs-testrpc has been renamed to ganache-cli

npm install -g ethereumjs-testrpc 
npm install -g truffle
npm install -g ganache-cli
npm install -g express
npm install -g mocha
npm install -g @openzeppelin/contracts

echo ====================================================
echo INSTALLING RESILIO
echo ====================================================

../components/300_resilio

echo ====================================================
echo VERSIONS
echo ====================================================

echo === NODE ===
nodejs -v
npm -v

echo === ETHEREUM ===
truffle version
ganache-cli --version
echo mocha
mocha --version
#express --version





